//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant
    {
        public int id { get; set; }
        public Nullable<int> id_register { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<int> id_laboratory_services { get; set; }
        public Nullable<int> id_insurance_company { get; set; }
        public Nullable<int> id_check { get; set; }
    
        public virtual CheckCompany CheckCompany { get; set; }
        public virtual Register Register { get; set; }
        public virtual Service Service { get; set; }
    }
}
