//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string fathersname { get; set; }
        public Nullable<System.TimeSpan> datebirth { get; set; }
        public Nullable<int> seriespassport { get; set; }
        public Nullable<int> numberpassport { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string numberpolicy { get; set; }
        public Nullable<int> typepolicy { get; set; }
        public Nullable<int> idcompany { get; set; }
        public string ip { get; set; }
        public Nullable<System.TimeSpan> lastenter { get; set; }
        public Nullable<int> id_register { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
