//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> data_created { get; set; }
        public string services { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_status_service { get; set; }
        public Nullable<System.TimeSpan> order_time { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Status_Services_ Status_Services_ { get; set; }
    }
}
