//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Accountant = new HashSet<Accountant>();
            this.Status_Services_ = new HashSet<Status_Services_>();
        }
    
        public int id { get; set; }
        public Nullable<int> servicecode { get; set; }
        public string servicename { get; set; }
        public Nullable<System.TimeSpan> timework { get; set; }
        public Nullable<int> id_assistant { get; set; }
        public string analyzer { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual LabAssistant LabAssistant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accountant> Accountant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status_Services_> Status_Services_ { get; set; }
    }
}
