//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Services_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status_Services_()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_service { get; set; }
        public Nullable<int> id_laborant { get; set; }
        public Nullable<int> id_analyzer { get; set; }
        public Nullable<System.TimeSpan> date { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
